apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: nginx-2
  name: nginx-2
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-2
  template:
    metadata:
      labels:
        app: nginx-2
    spec:
      containers:
      - name: nginx-2
        image: nginx:1
        ports:
        - name: http
          containerPort: 80

